### ISSUE TITLE
Nice tutorials, well done!

### ISSUE THREAD

**Issue by bztsrc** [isometimes/rpi4-osdev#1]
Hi,

Thanks for this amazing tutorial! It would be great if you had mentioned that partially based on my tutorials for the RPi3 (I can recognize my own code :-)).
https://github.com/bztsrc/raspi3-tutorial

There's nothing wrong with using that code, it is licensed under MIT. But if you could put attribution in your readme.md, then in return I would recommend this tutorial in my readme.md too!

Cheers,
bzt

**Comment by isometimes** [comment]
Hi,

Thanks for reaching out. I hadn't intended to mislead anyone into thinking this was my own original work, and of course I'm very happy to acknowledge you. That's added to the top-level README.md now at the end.

Your work is inspiring and is the only thing that gave me the confidence I needed to push ahead with producing these tutorials. As you'll have seen, life took over and I've kind of stalled (for now)... but I will return to them soon!

Thanks,
Adam
