### ISSUE TITLE
[SOLVED] Building on linux arm

### ISSUE THREAD

**Issue by SjVer** [isometimes/rpi4-osdev#12]
I'm following this (pretty amazing) tutorial on my rpi itself, rather than a windows or ubuntu pc. However, the building part is an issue. I've downloaded the "AArch64 ELF bare-metal target" for aarch64 but it doesn't work. Any idea on why? 
Thanks in advance!

output:
```
/bin/rm kernel8.elf *.o *.img > /dev/null 2> /dev/null || true
gcc-arm-compiler/bin/aarch64-none-elf-gcc -Wall -O2 -ffreestanding -nostdinc -nostdlib -nostartfiles -c boot.S -o boot.o
gcc-arm-compiler/bin/aarch64-none-elf-gcc: 1: gcc-arm-compiler/bin/aarch64-none-elf-gcc: ELF�0d@@��@8: not found
gcc-arm-compiler/bin/aarch64-none-elf-gcc: 7: gcc-arm-compiler/bin/aarch64-none-elf-gcc: Syntax error: "(" unexpected
make: *** [Makefile:9: boot.o] Error 2
```

PS: I've extracted the .tar.xz file in my project folder and renamed the directory to 'gcc-arm-compiler'. I've also made these changes in the makefile, where i replaced the GCCPATH

**Comment by isometimes** [comment]
Hi,

Great to hear from you!

The error suggests the gcc binary is somehow being executed as a shell script... That happens when the OS doesn't know how to run the ELF binary.

Can you try using that same gcc executable to compile a simple "hello world" C program? I suspect if you can make that work then the tutorial build will also work just fine.

My overwhelming hunch, however, is that you're running a 64-bit ELF executable on a 32-bit platform (Raspbian typically runs in 32-bit mode, sadly). You can check by typing "uname -a" at the command line. If it says armv7l rather than aarch64 then it's 32-bit.

I don't think Arm provide builds for 32-bit Linux hosted cross-compilers targeting AArch64... At this point you may need to build the compiler from source (eeek). Or maybe a 32-bit clang is available?

Thanks,
Adam

**Comment by isometimes** [comment]
Hi,

If you're using a 64-bit kernel now (as per your edit), the gcc you were originally using should now work.

Give it a go and see if the results differ...

If not, let me know and I'll spin up Raspbian later and see what I can do. I'm flying a bit blind here :)

Thanks,
Adam

**Comment by SjVer** [comment]
Progress is happening!

The previous errors don't occur anymore, though a new one does. It looks like an easy fix, if only i knew what that fix would be. Any clue?
```
sjoerdv@raspberrypi:~/Coding/OS/BareMetal $ make
/bin/rm kernel8.elf *.o *.img > /dev/null 2> /dev/null || true
gcc-arm-compiler/bin/aarch64-none-elf-gcc -Wall -O2 -ffreestanding -nostdinc -nostdlib -nostartfiles -c boot.S -o boot.o
make: gcc-arm-compiler/bin/aarch64-none-elf-gcc: Command not found
make: *** [Makefile:9: boot.o] Error 127
```

**Comment by SjVer** [comment]
They were already executable. I double checked and that's not the issue :/

**Comment by isometimes** [comment]
What's the output of:

file _gcc filename_

?

**Comment by SjVer** [comment]
```
aarch64-none-elf-gcc: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=3c46855d204859807af711270c8399be66ab5462, not stripped
```

**Comment by isometimes** [comment]
Two more tests:

1) Does /lib/ld-linux-aarch64.so.1 exist?

2) If you chdir into the directory with the gcc executable and type just _gcc --version_, what do you get?

A

**Comment by SjVer** [comment]
1:
nope.

2:
```
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by isometimes** [comment]
Sorry, I wasn't clear for 2).

You'll need to type:

./aarch64-none-elf-gcc --version

A

**Comment by isometimes** [comment]
Can I suggest you try this gcc compiler download instead?

https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-aarch64-aarch64-none-elf.tar.xz?revision=9611f84a-41b8-4eae-9c30-045c830f5337&la=en&hash=109566BAD01B49B8BED6E60956DAB59ADFABAE62

Let me know how that goes! I'm interested to hear the results...

**Comment by SjVer** [comment]
Bad news, it didn't work.
It appears to be the exact same as the other version of the compiler.

I'm not super knowledgeable of the topic of building, but is it an option to use e.g. gcc and nasm?

**Comment by SjVer** [comment]
GOOD NEWS!

I did some further investigation about the missing elf interpreter file, and after downloading and putting it in /lib things worked better!

now i just got a bunch of new errors tho:
```
sjoerdv@raspberrypi:~/Coding/OS/BareMetal $ make
/bin/rm kernel8.elf *.o *.img > /dev/null 2> /dev/null || true
gcc-arm-compiler/bin/aarch64-none-elf-gcc -Wall -O2 -ffreestanding -nostdinc -nostdlib -nostartfiles -c boot.S -o boot.o
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
gcc-arm-compiler/bin/aarch64-none-elf-gcc: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory
make: *** [Makefile:9: boot.o] Error 127
```

**Comment by isometimes** [comment]
I think you may be going down a rabbit hole with this approach. I'm just putting Raspbian on my Pi and seeing if I can come up with a better solution for you. Starting with 32-bit out-of-the-box and seeing how far I can get... I'd like to think this should be possible (and love a challenge!).

**Comment by isometimes** [comment]
I wonder if that's just a library path issue? You can specify the library path to gcc on the command line using the -L argument e.g. by adding _-L /usr/lib_ onto the end... Make sure that library directory is the one with libdl.so.2 in.

**Comment by SjVer** [comment]
But which directory is that?

**Comment by isometimes** [comment]
Try _locate libdl.so.2_ on the command line

**Comment by SjVer** [comment]
It's in multiple directories, but /usr/lib is one of them. I'll try that one then.

**Comment by SjVer** [comment]
btw, since adding `-L /usr/lib' after `make` appearently isn't the way to go, what should i modify exactly?

**Comment by SjVer** [comment]
My GCCFLAGS looks like this now: ```GCCFLAGS = -Wall -O2 -ffreestanding -nostdinc -nostdlib -nostartfiles -L /usr/lib```
But it makes no difference.

**Comment by isometimes** [comment]
The good news is that I've reproduced your issue! That means I can work on solving it (somehow!)...

**Comment by SjVer** [comment]
I'm incredibly happy to hear you've found a solution! You're quicker than i imagined :)
I'll read through the documentation and see if i can get it to work. I'll close the issue once it does.

I cannot thank you enough! 
Sjoerd

**Comment by isometimes** [comment]
There are a few decent posts in the Raspberry Pi forums on this issue. Here's a good example: https://www.raspberrypi.org/forums/viewtopic.php?t=298627. It comes down to the existence of the 64-bit loader and library files in userland. You can just mount the 64-bit beta image and gradually copy across the files to your standard install (with arm_64bit=1 in the config.txt so it boots with a 64-bit kernel). I've no idea which files will be needed though! I'm sure gcc will keep moaning until the right ones are there! ;-)

**Comment by SjVer** [comment]
Good news!

I followed your documentation to the point and it worked! I got some warnings, but they didn't seem to matter.
Looks like my problem is truly fixed now! :)

**Comment by SjVer** [comment]
Hey! Just a quick question (this will be the last).

Since I'm both compiling and running on the same device, do I really need to cross-compile?

**Comment by isometimes** [comment]
Possibly not...

Should be easy to test - just change the GCCPATH in the Makefile to point at the gcc binary that comes with Raspbian (probably /usr/bin). You will also need to modify the executable names that run through the Makefile e.g. aarch64-none-elf-gcc will become just gcc, aarch64-none-elf-ld will become ld etc.

Let me know how you get on!

**Comment by SjVer** [comment]
I tried it with someone else's example files, which worked. If I try it with e.g. part 5 of this tutorial it gives the following output:
```
sjoerdv@raspberrypi:~/Coding/OS/BareMetal $ make
/bin/rm kernel8.elf *.o *.img > /dev/null 2> /dev/null || true
gcc -Wall -O2 -ffreestanding -nostdinc -nostdlib -nostartfiles -c boot.S -o boot.o
boot.S: Assembler messages:
boot.S:7: Error: ARM register expected -- `mrs x1,mpidr_el1'
boot.S:8: Error: ARM register expected -- `and x1,x1,#3'
boot.S:9: Error: selected processor does not support `cbz x1,2f' in ARM mode
boot.S:11: Error: selected processor does not support `wfe' in ARM mode
boot.S:16: Error: ARM register expected -- `ldr x1,=_start'
boot.S:17: Error: immediate expression requires a # prefix -- `mov sp,x1'
boot.S:20: Error: ARM register expected -- `ldr x1,=__bss_start'
boot.S:21: Error: ARM register expected -- `ldr w2,=__bss_size'
boot.S:22: Error: selected processor does not support `cbz w2,4f' in ARM mode
boot.S:23: Error: ARM register expected -- `str xzr,[x1],#8'
boot.S:24: Error: ARM register expected -- `sub w2,w2,#1'
boot.S:25: Error: selected processor does not support `cbnz w2,3b' in ARM mode
make: *** [Makefile:9: boot.o] Error 1
```

**Comment by isometimes** [comment]
Was the other example using AArch64 assembly instructions? I suspect not. Not all code is created equal!

I just wouldn't go there. Cross-compilation is going to be your friend here... Otherwise, try and see whether you need to give gcc some command-line argument to target AArch64 etc.

Personally, I wouldn't bang my head against a brick wall when a solution exists!

**Comment by SjVer** [comment]
Copy that!😂

**Comment by SjVer** [comment]
You might wanna add a link to [this](https://wiki.osdev.org/GCC_Cross-Compiler) tutorial as an alternative to re-imaging the rpi. It shows you how to build the cross-compiler from source and works perfectly.

**Comment by isometimes** [comment]
Yes, that was my other option (I even mentioned it in passing in my first reply to you at the top of this thread!).

I didn't know how excited you'd be to build the compiler from source though, to be honest. Great that you did it :)

**Comment by SjVer** [comment]
I'm not saying that this solution is the best, because it definetly isn't. I just didn't really like the idea of trying to back up all my stuff from my 128GB sd card to my spare 16GB one.

**Comment by Orrexon** [comment]
Hi! I had a similar setup where I was building on the pi and connected it
to another pi via serial to usb. With the 64 bit raspberry pi OS Adams
tutorials worked really well using the native gcc compiler and the
assembler that comes with the 64 bit OS. You just dont need the path, I
could just build it straight away.

You can look at my make file to see the difference.

WARNING the code is not working atm since I was trying some things and then
I took a break continuing with a game and a little hobby parser BUT I
believe the make file is actually OK

Any way, it could possibly help to look at it, should just be the same as
Adams make file but with the native tools about one or 2 steps after the
game in Adams tutorial. I dont quite remember the status of the make file.
I will find my way back to the project evetually :)

Den tors 13 maj 2021 14:09SjoerdV ***@***.***> skrev:
