### ISSUE TITLE
demo of camera module

### ISSUE THREAD

**Issue by littlemonkey00** [isometimes/rpi4-osdev#24]
Hi，
    Are you interested in writing a demo showing the pictures captured by the camera module.

**Comment by isometimes** [comment]
Definitely! I don't know how feasible (everything's feasible depends on how much time...) it is, but I'll look into it 🙂

**Comment by littlemonkey00** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by isometimes** [comment]
Ok, this looks like an enormous amount of work (mainly due to lack of available documentation). I think I'm going to steer clear of this for now... I can see it being a really big time suck, sorry! :)
