### ISSUE TITLE
Will this tutorial work for Raspberry Pi 1 Model B (512MB RAM)

### ISSUE THREAD

**Issue by o92** [isometimes/rpi4-osdev#26]
Hi, 

Thanks for putting together this tutorial. I have a RPi 1 from 2012 with 512 MB RAM and wanted to follow your tutorial on it. Just wondering if it might work?

**Comment by isometimes** [comment]
Hi,

It definitely won't work without modifications, no. It wouldn't even work on a Pi 3 without mods. It will be a good exercise for you to work out what those modifications should be though! You'll definitely know the code well by the end of that journey!

Best,
Adam
