### ISSUE TITLE
Errata - Part 3 - Reference to edit of config.txt for TV

### ISSUE THREAD

**Issue by greenonline** [isometimes/rpi4-osdev#28]
Note that I am referring to the online tutorial on rps4os.com...

In [part 3](https://www.rpi4os.com/part3-helloworld/) it states:

> Do you remember that, back in the first tutorial, I had to edit the *config.txt* file on the SD card to get Raspbian up on my TV screen? Now we need to add a line to ensure that our UART connection will be reliable.

However, the first mention of `config.txt` is actually in [part 2](https://www.rpi4os.com/part2-building/) (*not* "back in the first tutorial") , and only in reference to running in 64 bit mode:

> We’ll now copy our kernel8.img onto the SD card. This name is meaningful and it signals to the RPi4 that we want it to boot in 64-bit mode. We can also force this by setting `arm_64bit` to a non-zero value in [config.txt](https://www.raspberrypi.org/documentation/configuration/config-txt/boot.md). Booting our OS into 64-bit mode will mean that we can take advantage of the larger memory capacity available to the RPi4.

So, where is the part about the TV screen? Is that missing from part 1? Or is it missing from part 2? The former seems most likely, although its being missing in part 2 would also make sense as that is where the screen is referred to (and expected to be black).

Please could you correct the online guide so that the edit to config.txt TV screen is shown and explained in which ever part each should be mentioned... and that the backreference to that (in part 3) is also accurate..?

Note that I haven't *yet* tried running any of the compiles or make files, nor made any code. I'm just reading and following your excellent (and interesting) guide - actually I've just started, and the above issue made me stop and scratch my head... 

Many thanks.

**Comment by isometimes** [comment]
Thanks for your detailed comments! I am travelling this weekend, but will address them
 as soon as I return on Monday 🙂

**Comment by greenonline** [comment]
Actually, I have just discovered the source of my confusion... google actually threw me on to the [second page](https://www.rpi4os.com/part1-bootstrapping/) of the tutorial (which is confusingly called "part 1").

However, after reading the github [Readme.md](https://github.com/isometimes/rpi4-osdev#readme) I realised that there is actually a page prior to that, which on the website can only be accessed (from the part one page) by changing the URL in the browser to https://www.rpi4os.com/. So this is (effectively) part zero (which equivalent to the `README.md`, and on that page, I can *now* see the lines:

> Hook up your RPi4 and make sure it boots into Raspbian. There are plenty of resources online to help you achieve/troubleshoot this. Getting Raspbian up will test that your hardware setup is working properly. Note: because I connected my RPi4 to my (not brilliant) TV, I needed to make an edit in the *config.txt* file on the SD card (setting the `hdmi_safe` parameter to 1) to ensure that I could see the screen. Without that, it was just black.

So, the confusion is basically due to fact that the part one page on the website (not the github site) not having any indication that there is a previous page before the part 1 page (there is no "previous page" link, or "back"/"back to part zero"/"back to introduction" link),.. if that makes sense. 

This confusion is compounded by google throwing visitors on to the part one page, rather than the part zero (or "introductory" page).

Possible fixes: 

- Add a page 1 of 15 indicator somewhere on the page
- Add a back to previous page link somewhere on the page
- Renumber the parts so part one is actually part two (which would/could/might be a pain to implement)
- Something else I haven't thought of

Hopefully all of that makes sense. And apologies for having to complain about a beautifully written tutorial.

**Comment by paulwratt** [comment]
it might be worth converting `hdmi_safe` to combine it with a direct link to the RPi docs page, as there are some other things you can do in `config.txt` that are specific to getting an acceptable TV output (and are referenced on those pages), but dont warrant further comment in the tutorial.

**Comment by isometimes** [comment]
@paulwratt Good suggestion, and I've updated the intro to include a link to the further video options.

To the wider issue, I'm still pondering what the right approach to backlinking etc. is... 🤔

**Comment by isometimes** [comment]
OK, temporary fix done to add a link back to the intro from part1. It doesn't solve the problem if you land on part14, for example, (Google has indexed all parts), so definitely something to think about more as I go on. I suspect a ToC would be useful if I could add it non-intrusively on each part...
