### ISSUE TITLE
Typo - part 8 - "very my"

### ISSUE THREAD

**Issue by greenonline** [isometimes/rpi4-osdev#30]
In [part 8](https://www.rpi4os.com/part8-breakout-ble/), The line towards the bottom, under **Connecting to our Breakout controller from the Raspberry Pi**, reads (the *emphasis* is mine to highlight the location):

> `gatttool` and `hcitool` on Raspbian turned out to be *very my* good friends!

should be

> `gatttool` and `hcitool` on Raspbian turned out to be *my very* good friends!

"my" and "very" are transposed.

**Comment by isometimes** [comment]
Merged PR, thanks!
