### ISSUE TITLE
Link - part 11 - Not hypertext

### ISSUE THREAD

**Issue by greenonline** [isometimes/rpi4-osdev#33]
On the page for [part 11](https://www.rpi4os.com/part11-breakout-smp/), the link to the video isn't hypertext. You have to right click and select "Go to..."

On the github page it appears as an embedded video, however on the rpi4os website it does not:

![Screen Shot 2022-07-05 at 17 11 31](https://user-images.githubusercontent.com/11710446/177371469-62db74b4-087c-465e-8481-959f1cbdd2d3.png)

**Comment by isometimes** [comment]
Yes - that's a current bug with GitHub's rendering of Markdown sadly. The GitHub Pages version shows an embedded video as intended. Look at the source file.

**Comment by isometimes** [comment]
If you have a PR that fixes it, I'll happily merge.

AGB
