### ISSUE TITLE
Page number - part 14 - Incorrect page reference on datasheet

### ISSUE THREAD

**Issue by greenonline** [isometimes/rpi4-osdev#34]
On [part 14](https://www.rpi4os.com/part14-spi-ethernet/), the SPIO register is referred to:

> Looking at the SPI0 register map on page 134, we see this reflected in our `REGS_SPI0` structure. This gives us handy access to the SPI0 peripheral’s memory-mapped registers.

The SPIO register (Table 159) is actually shown on [page 136](https://datasheets.raspberrypi.com/bcm2711/bcm2711-peripherals.pdf).

**Comment by isometimes** [comment]
Agreed. Will be fixed in next commit.
