### ISSUE TITLE
Explanation - part 14 - Active LOW

### ISSUE THREAD

**Issue by greenonline** [isometimes/rpi4-osdev#35]
On [part 14](https://www.rpi4os.com/part14-spi-ethernet/), you state:

> Through a bit of trial & error I discovered that when GPIO08 is clear, the device is selected, and when it’s set, the device is deselected. If you can explain this to me, I’d love to hear from you - frankly, I was just pleased to get it working, so I moved on!

This is because the Chip Select pin on the ENC28J60 is active LOW, so the board, upon which the IC is placed ,just brings this pin out, without using an invertor (to save costs).  You can see that the ENC28J60 is active LOW by looking at the datasheet of the [ENC28J60](https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/DataSheets/39662e.pdf): Note the /CS pin - the bar denotes active LOW. Hence GPIO08 must be LOW to enable the IC.

**Comment by isometimes** [comment]
Nice explanation, thank you! Coming in next commit 😄
