### ISSUE TITLE
Typo - Part 14 - arp.c - random close comment

### ISSUE THREAD

**Issue by greenonline** [isometimes/rpi4-osdev#36]
[arp.c](https://github.com/isometimes/rpi4-osdev/blob/master/part14-spi-ethernet/kernel/arp.c) [Line 108](https://github.com/isometimes/rpi4-osdev/blob/2b9e41259b7c956c8755e99dd196adac69ba2ee9/part14-spi-ethernet/kernel/arp.c#L108). There is a random `*/` at the end of the line, that isn't needed. As it is within a comment is doesn't affect the code obviously.

```none
   // The destination is broadcast - a MAC address of FF:FF:FF:FF:FF:FF */
```

**Comment by isometimes** [comment]
Quite correct! Will fix in next commit.
