### ISSUE TITLE
Improve framebuffer drawing -- dual buffering or other technique?

### ISSUE THREAD

**Issue by zuber99** [isometimes/rpi4-osdev#39]
I notice when i draw images that are quite large, take a long time in drawing all pixels.
Is there a way to improve this? I looked up into dual buffering technique but still not sure how to do that.

Otherwise what would allow best to draw images without lag or a sliding scanner?

**Comment by isometimes** [comment]
Have you looked into part12 at all? The WGT code I ported has some good tricks to speed up graphics to the extent that you can make a playable game.

If that's not fast enough, let me know exactly what you're trying to achieve and I'll try to advise you.

Thanks,
Adam
